### ISSUE TITLE
Slower than .filter()

### ISSUE THREAD

**Issue by soanvig** [Prestaul/fast-filter#1]
https://jsperf.com/fastfilter-vs-native-array-filter

array.filter
var result = subject.filter(isOdd);
68,505
±5.96% fastest

array.fastFilter
var result = subject.fastFilter(isOdd);
64,812
±3.60% 3% slower

Firefox 52

**Comment by Prestaul** [comment]
Interesting, I see about the same results in FF. Maybe FF has improved performance! 

I just ran some quick tests. In Internet Explorer 11 (on a VM) `fastFilter` is about 30% faster. In Chrome on Android, desktop Chrome (OS X), and Safari `fastFilter` still looks to be about twice the speed of `filter`:

```text
array.filter
var result = subject.filter(isOdd);
16,478
±1.12%
95% slower

array.fastFilter
var result = subject.fastFilter(isOdd);
312,045
±0.91%
fastest

Chrome 56.0.2924.87 (64-bit)
```

So, it currently looks like `fastFilter` may be ~5% slower than native `filter` in FF and ~95% faster in most other browsers. As always, your milage may vary.

**Comment by Prestaul** [comment]
@soanvig, thanks for bringing this to my attention. Let me know if there is something specific you think I should be doing to address this.
